# Generated by Django 3.0.5 on 2022-12-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_text',
            field=models.CharField(default=2, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pizza',
            name='pizza_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='topping',
            name='topping_name',
            field=models.CharField(max_length=50),
        ),
    ]
